var chai = require('chai');
var expect = chai.expect;
var factory = require('../src/factory.js');

describe('Factory', function () {
  it('is a function', function () {
    expect(factory).to.be.a('function')
  });

  describe('#attr', function () {
    it('sets the attributes', function () {

    })

    it('chainable', function () {

    })
  }); //#attr

  describe('when called', function () {
    describe('default', function () {
      it('returns an empty object', function () {

      });
    });

    describe('with blueprint set', function () {

      describe('as values', function () {
        it('returns an object with values same as the blueprint', function () {
        })
      });

      describe('as function', function () {
        it('returns an object with values generated by the function in the blueprint', function () {
        })
      });
    }) //with blueprint set

    describe('with arguments', function () {
      it('sets attributes', function () {

      });

      it('overrides attributes', function () {

      });
    });
  }) //when called
});
